# Generated by Django 4.2.11 on 2024-03-15 18:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='services',
            table=None,
        ),
    ]
