# Generated by Django 4.2.11 on 2024-03-15 18:54

import cloudinary.models
from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_about_profile_image_alter_about_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=djrichtextfield.models.RichTextField(max_length=10000),
        ),
    ]
