# Generated by Django 4.2.11 on 2024-03-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_updated_on_review_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='slug',
            field=models.SlugField(default='review', max_length=200, unique=True),
        ),
    ]
