# Generated by Django 4.2.11 on 2024-03-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_rename_rating_review_rating_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='review',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
