# Generated by Django 4.2.11 on 2024-03-18 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='booking',
        ),
    ]
