# Generated by Django 4.2.11 on 2024-03-18 17:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_delete_about'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0007_remove_review_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating_value',
        ),
        migrations.RemoveField(
            model_name='review',
            name='services',
        ),
        migrations.RemoveField(
            model_name='review',
            name='status',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.services'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
