# Generated by Django 4.2.11 on 2024-03-13 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
